// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import type { OAuthProvider } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        ...opts,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.signOut({ scope: "local" });
        const { data: sessionData, error: sessionError } = await supabase.auth.setSession(result.tokens);
        if (sessionError || !sessionData.session) {
          throw sessionError ?? new Error("Social sign-in did not return a fresh session.");
        }
        const { data: verified, error: verifyError } = await supabase.auth.getUser(
          sessionData.session.access_token,
        );
        if (verifyError || !verified.user || verified.user.id !== sessionData.session.user.id) {
          await supabase.auth.signOut({ scope: "local" });
          throw new Error("We could not confirm the social sign-in account.");
        }
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
