REVOKE EXECUTE ON FUNCTION public.admin_ban_user(uuid, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_moderation_log(integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_payout_queue() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_unban_user(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_warn_user(uuid, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.bill_stream_minute(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.block_banned_users() FROM anon;
REVOKE EXECUTE ON FUNCTION public.contribute_to_pool(uuid, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_bounty_pool(text, text, integer, text, double precision, double precision, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_coin_wallet_for_new_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.credit_coin_purchase(uuid, text, text, integer, integer, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.credit_purchase(uuid, text, text, integer, integer, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.end_stream_session(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_coin_wallet(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_credit_wallet(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.expire_stale_media() FROM anon;
REVOKE EXECUTE ON FUNCTION public.pin_community_post(uuid, integer, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.platform_metrics() FROM anon;
REVOKE EXECUTE ON FUNCTION public.pool_backer_counts(uuid[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_daily_engagement() FROM anon;
REVOKE EXECUTE ON FUNCTION public.request_coin_cashout(integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.request_credit_cashout(integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.start_stream_session(uuid, integer, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.tip_coins(uuid, integer, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.tip_credits(uuid, integer, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.top_reporters(integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.top_reporters_weekly(integer) FROM anon;