REVOKE EXECUTE ON FUNCTION public.accept_bounty_video(_video_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.adjust_wallet(_user_id uuid, _amount numeric, _kind text, _request_id uuid, _note text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_ban_user(_user_id uuid, _reason text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_moderation_log(_limit integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_payout_queue() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_unban_user(_user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_warn_user(_user_id uuid, _reason text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.award_xp(_user_id uuid, _amount integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.bill_stream_minute(_session_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.block_banned_users() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_chat_on_request(_request_key text, _user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_view_dispute(_request_id uuid, _user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.chat_participants(_request_key text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.close_expired_requests() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.complete_request_when_claim_approved() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.contribute_to_pool(_pool_id uuid, _amount integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_bounty_pool(_title text, _place text, _goal_credits integer, _kind text, _latitude double precision, _longitude double precision, _hours integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_coin_wallet_for_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.credit_coin_purchase(_user_id uuid, _session_id text, _package_id text, _coins integer, _amount_cents integer, _environment text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.credit_purchase(_user_id uuid, _session_id text, _package_id text, _coins integer, _amount_cents integer, _environment text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.credit_topup(_user_id uuid, _session_id text, _amount numeric, _environment text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.dispute_bounty(_request_id uuid, _reason text, _reason_code text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.dispute_bounty(_request_id uuid, _reason text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.end_stream_session(_session_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.enforce_request_content_moderation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ensure_coin_wallet(_user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ensure_credit_wallet(_user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.escrow_hold_on_request() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.escrow_refund_on_request_delete() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.escrow_release_on_approval() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.escrow_reserve_on_claim() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.escrow_submit_on_bounty_video() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.escrow_submit_on_media() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.expire_stale_media() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.explore_clips(_limit integer, _offset integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.global_feed_clips(_limit integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.grant_admin_for_verified_email() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.guard_request_cancellation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.hunter_trust(_user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.increment_clip_views(_video_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_review_staff(_user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.list_disputes() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.list_disputes_with_reasons() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.mark_chat_notifications_read(_request_key text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.mark_claim_submitted() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.mark_request_claimed() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.notify_chat_message() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.notify_nearby_hunters() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.onlookers_within_radius(_latitude double precision, _longitude double precision, _radius_miles numeric, _exclude_user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.payout_hold_on_request() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pin_community_post(_post_id uuid, _credits integer, _hours integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.platform_metrics() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pool_backer_counts(_pool_ids uuid[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.public_profile_card(_user_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.public_request_markers() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalc_rating() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_daily_engagement() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.reject_proof(_request_id uuid, _reason text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.request_cashout(_amount numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.request_coin_cashout(_coins integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.request_credit_cashout(_coins integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.request_earnings_payout(_amount numeric, _destination text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.request_is_live(_request_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.resolve_dispute(_request_id uuid, _award_spotter boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.resolve_payout(_payout_id uuid, _approve boolean, _note text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_moderator(_email text, _enabled boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.settle_escrows() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.start_stream_session(_host_id uuid, _credits_per_minute integer, _post_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.submit_instant_snippet(_video_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_wallet_balance_from_video() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.tip_coins(_receiver_id uuid, _amount integer, _transaction_type text, _request_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.tip_credits(_receiver_id uuid, _amount integer, _transaction_type text, _request_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.tip_hunter(_video_id uuid, _amount numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.top_reporters(_limit integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.top_reporters_weekly(_limit integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_bounty_boost() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_bounty_video() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_claim_insert() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_media_upload() FROM PUBLIC;